### ISSUE TITLE
Current 1.1.0 not working with LineageOS 14.1

### ISSUE THREAD

**Issue by nachtgeist** [robert7k/sipswitch#14]
The app is installed, however it doesn't show up in the widget list to be added to the start screen.
LineageOS 14.1 (2017-05-25) based on Android 7.1

How can I help to track this down?

**Comment by robert7k** [comment]
The current version is 1.1.1 and contains fixes for Android 7. Have you tried that?

**Comment by nachtgeist** [comment]
Yes
