### ISSUE TITLE
Resizing don't works correct

### ISSUE THREAD

**Issue by lucchinelli** [robert7k/sipswitch#15]
Hi Robert.
You widget is a wonderfull light implementation for using VoIP. All other apps are bigger and so I am choosing your widget from fdoid (v1.1.1) and it works very fine for me. I am using an Honor 4x from stock with OS 4.4.2 and EMUI 3.0 as lancher. 
Afer I installed the widget I could only see the “toogle“ button and the size of the widget was 2x1. I find out if I want see the “configure“ button I have to resize the widget in min. (!) to 3x1. For 2x1 and 1x1 only the toogle button is visible.
Is the correct? It would very nice if I could also use both buttons together in a size of 2x1. Can you check this please.
Thanks in advance.
Marco

**Comment by robert7k** [comment]
Sorry for the delayed response.

Usually, the widget should show two buttons for 2x1 and larger, and one button for 1x1.

Maybe that has something to do with the resolution of your device, but I would have to check that. What's the resolution of your device's display?

**Comment by lucchinelli** [comment]
Hi Robert.
Thanks for your response. Here are the specifications of the Honor 4x incl. the display-resolution:
Model: Che2-L11
Android: 4.4.2; C432B120; SDK19
Display: 1280 x 720; DPI: 320
GPU: Mali-450 MP; ARM; OpenGL ES-CM 1.1; OpenGL ES 2.0
Processor: ARMv7 Processor rev 3 (v7l) hi6210sft
I hope it helps you.
Marco

**Comment by madmuffin1** [comment]
Hey @lucchinelli , I had that issue too and fixed it in my MR #16.

**Comment by robert7k** [comment]
Should be fixed in version 1.1.2
