### ISSUE TITLE
Call alphanumeric extensions

### ISSUE THREAD

**Issue by narcisgarcia** [robert7k/sipswitch#18]
I'm using Android 4.4 and it seems to depend on phone application exclusively to specify call destination. Phone app only allows to type in numbers and basic signs (+-#*)
Is there some way to specify an alphanumeric SIP target for a call?

If my SIP subscription is by alphanumeric username (same as telephonic net extension), can be this preventing to receive calls?

Something specific when using Asterisk server?

**Comment by robert7k** [comment]
This is unrelated to the widget, as the widget only toggles whether to use SIP for a call or not. Therefore, I'm closing this issue.

>  Is there some way to specify an alphanumeric SIP target for a call?

Have you tried saving them into your phone book?

> If my SIP subscription is by alphanumeric username (same as telephonic net extension), can be this preventing to receive calls?

This shouldn't be the case.

**Comment by narcisgarcia** [comment]
> > Is there some way to specify an alphanumeric SIP target for a call?
> 
> Have you tried saving them into your phone book?

Yes it works by adding "Internet call" field to the contact!
Thank you.
